
available_reciters = [
    "إبراهيم الأخضر", "إبراهيم الجبرين", "إبراهيم العسيري", "شيخ أبو بكر الشاطري",
    "أحمد بن علي العجمي", "أحمد الحواشي", "أحمد سعود", "أحمد صابر",
    "أحمد نعينع", "أكرم العلاقمي", "إدريس أبكر", "الزين محمد أحمد",
    "العشري عمران", "توفيق الصايغ", "جمال شاكر عبدالله", "حمد الدغريري",
    "خالد الجليل", "خالد القحطاني", "خالد عبدالكافي", "خالد الوهيبي",
    "خليفة الطنيجي", "داود حمزة", "رشيد بلعالية", "زكريا حمامة",
    "سعد الغامدي", "سعود الشريم", "سهل ياسين", "زكي داغستاني",
    "سامي الحسن", "سامي الدوسري", "سيد رمضان", "شعبان الصياد",
    "شيرزاد عبدالرحمن طاهر", "صابر عبدالحكم", "صالح الصاهود", "صالح آل طالب",
    "صالح الهبدان", "صلاح البدير", "صلاح الهاشم", "صلاح بو خاطر",
    "عادل ريان", "عبدالبارئ الثبيتي", "عبدالبارئ محمد", "عبدالباسط عبدالصمد",
    "عبدالرحمن السديس", "عبدالعزيز الأحمد", "عبدالعزيز الزهراني", "عبدالله البريمي",
    "عبدالله البعيجان", "عبدالله المطرود", "عبدالله بصفر", "عبدالله خياط",
    "عبدالله عواد الجهني", "عبدالله غيلان", "عبدالرشيد صوفي", "عبدالمحسن الحارثي",
    "عبدالمحسن القاسم", "عبدالمحسن العسكر", "عبدالمحسن العبيكان", "عبدالهادي أحمد كناكري",
    "عبدالودود حنيف", "عبدالولي الأركاني", "علي أبو هاشم", "علي بن عبدالرحمن الحذيفي",
    "علي جابر", "علي حجاج السويسي", "عماد زهير حافظ", "فارس عباد",
    "فهد العتيبي", "فهد الكندري", "فواز الكعبي", "لافي العوني",
    "ناصر القطامي", "نبيل الرفاعي", "نعمة الحسان", "هاني الرفاعي",
    "وليد الدليمي", "ياسر الدوسري", "ياسر القرشي", "ياسر الفيلكاوي",
    "يحيى حوا", "يوسف الشويعي", "ماجد العنزي", "مالك شيبة الحمد",
    "ماهر المعيقلي", "محمد البراك", "محمد الطبلاوي", "محمد اللحيدان",
    "محمد المحيسني", "محمد أيوب", "محمد صالح عالم شاه", "محمد جبريل",
    "محمد صديق المنشاوي", "محمد عبدالكريم", "محمود خليل الحصري", "محمود علي البنا",
    "مشاري العفاسي", "مصطفى إسماعيل", "مصطفى اللاهوني", "مصطفى رعد العزاوي",
    "معمر الأندونيسي", "ماجد الزامل", "ماهر شخاشيرو", "محمد المنشد",
    "ياسر سلامة", "أخيل عبدالحي روا", "أستاذ زامري", "خالد المهنا",
    "عادل الكلباني", "موسى بلال", "حسين آل الشيخ", "حاتم فريد الواعر",
    "إبراهيم الجرمي", "محمود الرفاعي", "ناصر العبيد", "واصل المذن",
    "إبراهيم الدوسري", "جمعان العصيمي", "رضية عبدالرحمن", "رقية سولونق",
    "سابينة مامات", "سيدين عبدالرحمن", "عبدالغني عبدالله", "عبدالله فهمي",
    "محمد الحافظ", "محمد حفص علي", "محمد خير النور", "يوسف بن نوح أحمد",
    "جمال الدين الزيلعي", "معيض الحارثي", "محمد رشاد الشريف", "أحمد الطرابلسي",
    "عبدالله الكندري", "أحمد عامر", "إبراهيم السعدان", "أحمد الحذيفي",
    "محمد عثمان خان", "يوسف الدغوش", "وشيار حيدر اربيلي", "عثمان الأنصاري",
    "بندر بليله", "خالد الشريمي", "وديع اليمني", "رعد محمد الكردي",
    "عبدالرحمن العوسي", "خالد الغامدي", "رمضان شكور", "عبدالمجيد الأركاني",
    "محمد خليل القارئ", "رامي الدعيس", "هزاع البلوشي", "عبدالرحمن الماجد",
    "سلمان العتيبي", "محمد رفعت", "عبدالله الموسى", "عبدالله الخلف",
    "منصور السالمي", "صلاح مصلي", "خالد الشارخ", "ناصر العصفور",
    "أحمد السويلم", "إسلام صبحي", "بدر التركي", "هيثم الجدعاني",
    "ناصر الماجد", "أحمد خليل شاهين", "محمد البخيت", "سعد المقرن",
    "أحمد النفيس", "عمر الدريويز", "عبدالعزيز العسيري", "أحمد ديبان",
    "عبدالله كامل", "بيشه وا قادر الكردي", "نذير المالكي", "محمود عبدالحكم",
    "عبدالرحمن السويّد", "عبدالإله بن عون", "أحمد طالب بن حميد", "عبدالله بخاري",
    "عبدالعزيز التركي", "مختار الحاج", "عبدالله عبدل", "أحمد عيسى المعصراوي",
    "هاشم أبو دلال", "فؤاد الخامري", "سيد أحمد هاشمي", "خالد كريم محمدي",
    "صالح الشمراني", "مال الله عبدالرحمن الجابر", "سلمان الصديق", "حسن صالح",
    "عبدالرحمن الشحات", "عيسى عمر سناكو", "هارون بقائي", "فيصل الهاجري",
    "أنس العمادي", "عبدالملك العسكر", "عبدالكريم الحازمي", "عبدالله المشعل"
]

available_urls = [
    "https://server6.mp3quran.net/akdr/", "https://server6.mp3quran.net/jbreen/", "https://server6.mp3quran.net/3siri/", "https://server11.mp3quran.net/shatri/",
    "https://server10.mp3quran.net/ajm/", "https://server11.mp3quran.net/hawashi/", "https://server11.mp3quran.net/saud/", "https://server8.mp3quran.net/saber/",
    "https://server11.mp3quran.net/ahmad_nu/", "https://server9.mp3quran.net/akrm/", "https://server6.mp3quran.net/abkr/", "https://server9.mp3quran.net/alzain/",
    "https://server9.mp3quran.net/omran/", "https://server6.mp3quran.net/twfeeq/", "https://server6.mp3quran.net/jamal/", "https://server6.mp3quran.net/hamad/",
    "https://server10.mp3quran.net/jleel/", "https://server10.mp3quran.net/qht/", "https://server11.mp3quran.net/kafi/", "https://server11.mp3quran.net/whabi/",
    "https://server12.mp3quran.net/tnjy/", "https://server9.mp3quran.net/hamza/", "https://server6.mp3quran.net/bl3/", "https://server9.mp3quran.net/zakariya/",
    "https://server7.mp3quran.net/s_gmd/", "https://server7.mp3quran.net/shur/", "https://server6.mp3quran.net/shl/", "https://server9.mp3quran.net/zaki/",
    "https://server8.mp3quran.net/sami_hsn/", "https://server8.mp3quran.net/sami_dosr/", "https://server12.mp3quran.net/sayed/", "https://server11.mp3quran.net/shaban/",
    "https://server12.mp3quran.net/taher/", "https://server12.mp3quran.net/hkm/", "https://server8.mp3quran.net/sahood/", "https://server9.mp3quran.net/tlb/",
    "https://server6.mp3quran.net/habdan/", "https://server6.mp3quran.net/s_bud/", "https://server12.mp3quran.net/salah_hashim_m/", "https://server8.mp3quran.net/bu_khtr/",
    "https://server8.mp3quran.net/ryan/", "https://server6.mp3quran.net/thubti/", "https://server12.mp3quran.net/bari/", "https://server7.mp3quran.net/basit/",
    "https://server11.mp3quran.net/sds/", "https://server11.mp3quran.net/a_ahmed/", "https://server9.mp3quran.net/zahrani/", "https://server8.mp3quran.net/brmi/",
    "https://server8.mp3quran.net/buajan/", "https://server8.mp3quran.net/mtrod/", "https://server6.mp3quran.net/bsfr/", "https://server12.mp3quran.net/kyat/",
    "https://server13.mp3quran.net/jhn/", "https://server8.mp3quran.net/gulan/", "https://server16.mp3quran.net/soufi/Rewayat-Hafs-A-n-Assem/", "https://server6.mp3quran.net/mohsin_harthi/",
    "https://server8.mp3quran.net/qasm/", "https://server6.mp3quran.net/askr/", "https://server12.mp3quran.net/obk/", "https://server6.mp3quran.net/kanakeri/",
    "https://server8.mp3quran.net/wdod/", "https://server6.mp3quran.net/arkani/", "https://server9.mp3quran.net/abo_hashim/", "https://server9.mp3quran.net/hthfi/",
    "https://server11.mp3quran.net/a_jbr/", "https://server9.mp3quran.net/hajjaj/", "https://server6.mp3quran.net/hafz/", "https://server8.mp3quran.net/frs_a/",
    "https://server8.mp3quran.net/fahad_otibi/", "https://server11.mp3quran.net/kndri/", "https://server8.mp3quran.net/fawaz/", "https://server6.mp3quran.net/lafi/",
    "https://server6.mp3quran.net/qtm/", "https://server9.mp3quran.net/nabil/", "https://server8.mp3quran.net/namh/", "https://server8.mp3quran.net/hani/",
    "https://server8.mp3quran.net/dlami/", "https://server11.mp3quran.net/yasser/", "https://server9.mp3quran.net/qurashi/", "https://server6.mp3quran.net/fyl/",
    "https://server12.mp3quran.net/yahya/", "https://server9.mp3quran.net/yousef/", "https://server8.mp3quran.net/majd_onazi/", "https://server9.mp3quran.net/shaibat/",
    "https://server12.mp3quran.net/maher/", "https://server13.mp3quran.net/braak/", "https://server12.mp3quran.net/tblawi/", "https://server8.mp3quran.net/lhdan/",
    "https://server11.mp3quran.net/mhsny/", "https://server8.mp3quran.net/ayyub/", "https://server12.mp3quran.net/shah/", "https://server8.mp3quran.net/jbrl/",
    "https://server10.mp3quran.net/minsh/", "https://server12.mp3quran.net/m_krm/", "https://server13.mp3quran.net/husr/", "https://server8.mp3quran.net/bna/",
    "https://server8.mp3quran.net/afs/", "https://server8.mp3quran.net/mustafa/", "https://server6.mp3quran.net/lahoni/", "https://server8.mp3quran.net/ra3ad/",
    "https://server6.mp3quran.net/muamr/", "https://server9.mp3quran.net/zaml/", "https://server10.mp3quran.net/shaksh/", "https://server10.mp3quran.net/monshed/",
    "https://server12.mp3quran.net/salamah/Rewayat-Hafs-A-n-Assem/", "https://server12.mp3quran.net/malaysia/akil/", "https://server12.mp3quran.net/malaysia/zamri/", "https://server11.mp3quran.net/mohna/",
    "https://server8.mp3quran.net/a_klb/", "https://server11.mp3quran.net/bilal/", "https://server11.mp3quran.net/alshaik/", "https://server11.mp3quran.net/hatem/",
    "https://server11.mp3quran.net/jormy/", "https://server11.mp3quran.net/mrifai/", "https://server11.mp3quran.net/obaid/", "https://server11.mp3quran.net/wasel/Rewayat-Hafs-A-n-Assem/",
    "https://server10.mp3quran.net/ibrahim_dosri/Rewayat-Hafs-A-n-Assem/", "https://server6.mp3quran.net/jaman/", "https://server12.mp3quran.net/malaysia/rziah/", "https://server12.mp3quran.net/malaysia/rogiah/",
    "https://server12.mp3quran.net/malaysia/mamat/", "https://server12.mp3quran.net/malaysia/sideen/", "https://server12.mp3quran.net/malaysia/abdulgani/", "https://server12.mp3quran.net/malaysia/fhmi/",
    "https://server12.mp3quran.net/malaysia/hafz/", "https://server12.mp3quran.net/malaysia/hfs/", "https://server12.mp3quran.net/malaysia/nor/", "https://server8.mp3quran.net/noah/",
    "https://server11.mp3quran.net/zilaie/", "https://server8.mp3quran.net/harthi/", "https://server10.mp3quran.net/rashad/", "https://server10.mp3quran.net/trabulsi/",
    "https://server10.mp3quran.net/Abdullahk/", "https://server10.mp3quran.net/Aamer/", "https://server10.mp3quran.net/IbrahemSadan/", "https://server8.mp3quran.net/ahmad_huth/",
    "https://server6.mp3quran.net/khan/", "https://server7.mp3quran.net/dgsh/", "https://server11.mp3quran.net/wishear/", "https://server11.mp3quran.net/Othmn/",
    "https://server6.mp3quran.net/balilah/", "https://server12.mp3quran.net/shoraimy/", "https://server6.mp3quran.net/wdee3/", "https://server6.mp3quran.net/kurdi/",
    "https://server6.mp3quran.net/aloosi/", "https://server6.mp3quran.net/ghamdi/", "https://server6.mp3quran.net/shakoor/", "https://server7.mp3quran.net/m_arkani/",
    "https://server8.mp3quran.net/m_qari/", "https://server6.mp3quran.net/rami/", "https://server11.mp3quran.net/hazza/", "https://server10.mp3quran.net/a_majed/",
    "https://server11.mp3quran.net/salman/", "https://server14.mp3quran.net/refat/", "https://server14.mp3quran.net/mousa/Rewayat-Hafs-A-n-Assem/", "https://server14.mp3quran.net/khalf/",
    "https://server14.mp3quran.net/mansor/", "https://server14.mp3quran.net/musali/", "https://server14.mp3quran.net/sharekh/", "https://server14.mp3quran.net/alosfor/",
    "https://server14.mp3quran.net/swlim/Rewayat-Hafs-A-n-Assem/", "https://server14.mp3quran.net/islam/Rewayat-Hafs-A-n-Assem/", "https://server10.mp3quran.net/bader/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/hitham/Rewayat-Hafs-A-n-Assem/",
    "https://server14.mp3quran.net/nasser_almajed/", "https://server16.mp3quran.net/shaheen/Rewayat-Hafs-A-n-Assem/", "https://server14.mp3quran.net/bukheet/", "https://server16.mp3quran.net/saad/Rewayat-Hafs-A-n-Assem/",
    "https://server16.mp3quran.net/nufais/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/darweez/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/abdulazizasiri/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/deban/Rewayat-Hafs-A-n-Assem/",
    "https://server16.mp3quran.net/kamel/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/peshawa/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net//nathier/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/m_abdelhakam/Rewayat-Hafs-A-n-Assem/",
    "https://server16.mp3quran.net/a_swaiyd/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/a_binaoun/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/a_binhameed/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/a_bukhari/Rewayat-Hafs-A-n-Assem/",
    "https://server16.mp3quran.net/a_turki/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/mukhtar_haj/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/a_abdl/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/a_maasaraawi/Rewayat-Hafs-A-n-Assem/",
    "https://server16.mp3quran.net/h_abudalal/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/f_khamery/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/s_hashemi/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/kh_mohammadi/Rewayat-Hafs-A-n-Assem/",
    "https://server16.mp3quran.net/shamrani/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/mal-allah_jaber/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/s_sadeiq/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/h_saleh/Rewayat-Hafs-A-n-Assem/",
    "https://server16.mp3quran.net/a_alshahhat/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/i_sanankoua/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/h_baqai/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/f_hajry/Rewayat-Hafs-A-n-Assem/",
    "https://server16.mp3quran.net/a_alemadi/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/a_alaskar/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/a_alhazmi/Rewayat-Hafs-A-n-Assem/", "https://server16.mp3quran.net/a-almishal/Rewayat-Hafs-A-n-Assem/"
]

data_souar = {
    "الفاتحة": "001",
    "البقرة": "002",
    "آل عمران": "003",
    "النساء": "004",
    "المائدة": "005",
    "الأنعام": "006",
    "الأعراف": "007",
    "الأنفال": "008",
    "التوبة": "009",
    "يونس": "010",
    "هود": "011",
    "يوسف": "012",
    "الرعد": "013",
    "إبراهيم": "014",
    "الحجر": "015",
    "النحل": "016",
    "الإسراء": "017",
    "الكهف": "018",
    "مريم": "019",
    "طه": "020",
    "الأنبياء": "021",
    "الحج": "022",
    "المؤمنون": "023",
    "النور": "024",
    "الفرقان": "025",
    "الشعراء": "026",
    "النمل": "027",
    "القصص": "028",
    "العنكبوت": "029",
    "الروم": "030",
    "لقمان": "031",
    "السجدة": "032",
    "الأحزاب": "033",
    "سبأ": "034",
    "فاطر": "035",
    "يس": "036",
    "الصافات": "037",
    "ص": "038",
    "الزمر": "039",
    "غافر": "040",
    "فصلت": "041",
    "الشورى": "042",
    "الزخرف": "043",
    "الدخان": "044",
    "الجاثية": "045",
    "الأحقاف": "046",
    "محمد": "047",
    "الفتح": "048",
    "الحجرات": "049",
    "ق": "050",
    "الذاريات": "051",
    "الطور": "052",
    "النجم": "053",
    "القمر": "054",
    "الرحمن": "055",
    "الواقعة": "056",
    "الحديد": "057",
    "المجادلة": "058",
    "الحشر": "059",
    "الممتحنة": "060",
    "الصف": "061",
    "الجمعة": "062",
    "المنافقون": "063",
    "التغابن": "064",
    "الطلاق": "065",
    "التحريم": "066",
    "الملك": "067",
    "القلم": "068",
    "الحاقة": "069",
    "المعارج": "070",
    "نوح": "071",
    "الجن": "072",
    "المزمل": "073",
    "المدثر": "074",
    "القيامة": "075",
    "الإنسان": "076",
    "المرسلات": "077",
    "النبأ": "078",
    "النازعات": "079",
    "عبس": "080",
    "التكوير": "081",
    "الانفطار": "082",
    "المطففين": "083",
    "الانشقاق": "084",
    "البروج": "085",
    "الطارق": "086",
    "الأعلى": "087",
    "الغاشية": "088",
    "الفجر": "089",
    "البلد": "090",
    "الشمس": "091",
    "الليل": "092",
    "الضحى": "093",
    "الشرح": "094",
    "التين": "095",
    "العلق": "096",
    "القدر": "097",
    "البينة": "098",
    "الزلزلة": "099",
    "العاديات": "100",
    "القارعة": "101",
    "التكاثر": "102",
    "العصر": "103",
    "الهمزة": "104",
    "الفيل": "105",
    "قريش": "106",
    "الماعون": "107",
    "الكوثر": "108",
    "الكافرون": "109",
    "النصر": "110",
    "المسد": "111",
    "الإخلاص": "112",
    "الفلق": "113",
    "الناس": "114",
}

dict_souar = [
    "الفاتحة", 
    "البقرة", 
    "آل عمران", 
    "النساء", 
    "المائدة", 
    "الأنعام", 
    "الأعراف", 
    "الأنفال", 
    "التوبة", 
    "يونس", 
    "هود", 
    "يوسف", 
    "الرعد", 
    "إبراهيم", 
    "الحجر", 
    "النحل", 
    "الإسراء", 
    "الكهف", 
    "مريم", 
    "طه", 
    "الأنبياء", 
    "الحج", 
    "المؤمنون", 
    "النور", 
    "الفرقان", 
    "الشعراء", 
    "النمل", 
    "القصص", 
    "العنكبوت", 
    "الروم", 
    "لقمان", 
    "السجدة", 
    "الأحزاب", 
    "سبأ", 
    "فاطر", 
    "يس", 
    "الصافات", 
    "ص", 
    "الزمر", 
    "غافر", 
    "فصلت", 
    "الشورى", 
    "الزخرف", 
    "الدخان", 
    "الجاثية", 
    "الأحقاف", 
    "محمد", 
    "الفتح", 
    "الحجرات", 
    "ق", 
    "الذاريات", 
    "الطور", 
    "النجم", 
    "القمر", 
    "الرحمن", 
    "الواقعة", 
    "الحديد", 
    "المجادلة", 
    "الحشر", 
    "الممتحنة", 
    "الصف", 
    "الجمعة", 
    "المنافقون", 
    "التغابن", 
    "الطلاق", 
    "التحريم", 
    "الملك", 
    "القلم", 
    "الحاقة", 
    "المعارج", 
    "نوح", 
    "الجن", 
    "المزمل", 
    "المدثر", 
    "القيامة", 
    "الإنسان", 
    "المرسلات", 
    "النبأ", 
    "النازعات", 
    "عبس", 
    "التكوير", 
    "الانفطار", 
    "المطففين", 
    "الانشقاق", 
    "البروج", 
    "الطارق", 
    "الأعلى", 
    "الغاشية", 
    "الفجر", 
    "البلد", 
    "الشمس", 
    "الليل", 
    "الضحى", 
    "الشرح", 
    "التين", 
    "العلق", 
    "القدر", 
    "البينة", 
    "الزلزلة", 
    "العاديات", 
    "القارعة", 
    "التكاثر", 
    "العصر", 
    "الهمزة", 
    "الفيل", 
    "قريش", 
    "الماعون", 
    "الكوثر", 
    "الكافرون", 
    "النصر", 
    "المسد", 
    "الإخلاص", 
    "الفلق", 
    "الناس"
]
